version: '3'
services:
    openresty:
        image: openresty/openresty:buster-fat
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./conf.d:/etc/nginx/conf.d